# Generated by Django 2.2.7 on 2019-12-06 12:00
import sys

from django.db import migrations


def forward(apps, schema_editor):
    Warehouse = apps.get_model("warehouse", "Warehouse")
    if Warehouse.objects.exists():
        return

    Site = apps.get_model("sites", "Site")
    ShippingZone = apps.get_model("shipping", "ShippingZone")
    site_settings = Site.objects.get_current().settings
    company_address = site_settings.company_address
    if company_address is None:
        msg = """\n
        To proceed you need address that can be assigned to default Warehouse object.
        Please create Warehouse in the dashboard or at add company address in dashboard.
        """
        print(msg)
        sys.exit(3)
    address = company_address
    address.pk = None
    address.save()
    warehouse = Warehouse.objects.create(address=address)
    warehouse.shipping_zones.add(*ShippingZone.objects.all())


def backward(apps, schema_editor):
    Warehouse = apps.get_model("warehouse", "Warehouse")
    Warehouse.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_auto_20191205_0753"),
        ("site", "0025_auto_20191024_0552"),
        ("shipping", "0017_django_price_2"),
    ]

    # operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
    operations = [migrations.RunPython(forward, backward)]
